# Generated by Django 5.0.7 on 2024-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0006_tag_order_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='django1.tag'),
        ),
    ]
