# Generated by Django 5.0.7 on 2024-07-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0008_alter_customer_phone_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
